[package]
name = "banana-runtime"
version = "0.1.0-dev"
authors = ["Francis Hor <francishor@outlook.com>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://connesis.com"
repository = ""

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }

pallet-aura = { version = "2.0.0-dev", default-features = false, package = "pallet-aura", path = "../vendor/frontier/vendor/substrate/frame/aura" }
pallet-balances = { version = "2.0.0-dev", default-features = false, package = "pallet-balances", path = "../vendor/frontier/vendor/substrate/frame/balances" }
frame-support = { version = "2.0.0-dev", default-features = false, path = "../vendor/frontier/vendor/substrate/frame/support" }
pallet-grandpa = { version = "2.0.0-dev", default-features = false, package = "pallet-grandpa", path = "../vendor/frontier/vendor/substrate/frame/grandpa" }
pallet-randomness-collective-flip = { version = "2.0.0-dev", default-features = false, package = "pallet-randomness-collective-flip", path = "../vendor/frontier/vendor/substrate/frame/randomness-collective-flip" }
pallet-sudo = { version = "2.0.0-dev", default-features = false, package = "pallet-sudo", path = "../vendor/frontier/vendor/substrate/frame/sudo" }
frame-system = { version = "2.0.0-dev", default-features = false, package = "frame-system", path = "../vendor/frontier/vendor/substrate/frame/system" }
pallet-timestamp = { version = "2.0.0-dev", default-features = false, package = "pallet-timestamp", path = "../vendor/frontier/vendor/substrate/frame/timestamp" }
pallet-transaction-payment = { version = "2.0.0-dev", default-features = false, package = "pallet-transaction-payment", path = "../vendor/frontier/vendor/substrate/frame/transaction-payment" }
frame-ethereum = { version = "0.1.0", default-features = false, package = "pallet-ethereum", path = "../vendor/frontier/frame/ethereum" }
frame-evm = { version = "2.0.0-dev", default-features = false, package = "pallet-evm", path = "../vendor/frontier/vendor/substrate/frame/evm" }
frame-executive = { version = "2.0.0-dev", default-features = false, path = "../vendor/frontier/vendor/substrate/frame/executive" }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-api = { version = "2.0.0-dev", default-features = false, path = "../vendor/frontier/vendor/substrate/primitives/api" }
sp-block-builder = { path = "../vendor/frontier/vendor/substrate/primitives/block-builder", default-features = false, version = "2.0.0-dev"}
sp-consensus-aura = { version = "0.8.0-dev", default-features = false, path = "../vendor/frontier/vendor/substrate/primitives/consensus/aura" }
sp-core = { version = "2.0.0-dev", default-features = false, path = "../vendor/frontier/vendor/substrate/primitives/core" }
sp-inherents = { path = "../vendor/frontier/vendor/substrate/primitives/inherents", default-features = false, version = "2.0.0-dev"}
sp-io = { version = "2.0.0-dev", default-features = false, path = "../vendor/frontier/vendor/substrate/primitives/io" }
sp-offchain = { version = "2.0.0-dev", default-features = false, path = "../vendor/frontier/vendor/substrate/primitives/offchain" }
sp-runtime = { version = "2.0.0-dev", default-features = false, path = "../vendor/frontier/vendor/substrate/primitives/runtime" }
sp-session = { version = "2.0.0-dev", default-features = false, path = "../vendor/frontier/vendor/substrate/primitives/session" }
sp-std = { version = "2.0.0-dev", default-features = false, path = "../vendor/frontier/vendor/substrate/primitives/std" }
sp-transaction-pool = { version = "2.0.0-dev", default-features = false, path = "../vendor/frontier/vendor/substrate/primitives/transaction-pool" }
sp-version = { version = "2.0.0-dev", default-features = false, path = "../vendor/frontier/vendor/substrate/primitives/version" }
frame-system-rpc-runtime-api = { version = "2.0.0-dev", default-features = false, path = "../vendor/frontier/vendor/substrate/frame/system/rpc/runtime-api/" }
pallet-transaction-payment-rpc-runtime-api = { version = "2.0.0-dev", default-features = false, path = "../vendor/frontier/vendor/substrate/frame/transaction-payment/rpc/runtime-api/" }
frontier-rpc-primitives = { default-features = false, path = "../vendor/frontier/rpc/primitives" }

[build-dependencies]
wasm-builder-runner = { version = "1.0.5", package = "substrate-wasm-builder-runner", path = "../vendor/frontier/vendor/substrate/utils/wasm-builder-runner" }

[features]
default = ["std"]
std = [
	"pallet-aura/std",
	"pallet-balances/std",
	"codec/std",
	"frame-executive/std",
	"frame-support/std",
	"pallet-grandpa/std",
	"pallet-randomness-collective-flip/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"pallet-sudo/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"frame-ethereum/std",
	"frame-evm/std",
	"frame-system-rpc-runtime-api/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"frontier-rpc-primitives/std",
]
