[package]
name = "banana-node"
version = "0.1.0-dev"
authors = ["Francis Hor <francishor@outlook.com>"]
description = "Substrate Banana Chain"
edition = "2018"
license = "Apache-2.0"
build = "build.rs"
homepage = "https://connesis.com"
repository = ""

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.4"
log = "0.4.8"
structopt = "0.3.8"
jsonrpc-core = "14.0.3"
serde_json = "1.0"

sp-api = { version = "2.0.0-dev", path = "../vendor/frontier/vendor/substrate/primitives/api" }
sp-blockchain = { version = "2.0.0-dev", path = "../vendor/frontier/vendor/substrate/primitives/blockchain" }
sc-rpc-api = { version = "0.8.0-dev", path = "../vendor/frontier/vendor/substrate/client/rpc-api" }
sc-rpc = { version = "2.0.0-dev", path = "../vendor/frontier/vendor/substrate/client/rpc" }
substrate-frame-rpc-system = { version = "2.0.0-dev", path = "../vendor/frontier/vendor/substrate/utils/frame/rpc/system" }
pallet-transaction-payment-rpc = { version = "2.0.0-dev", path = "../vendor/frontier/vendor/substrate/frame/transaction-payment/rpc/" }
sc-cli = { version = "0.8.0-dev", path = "../vendor/frontier/vendor/substrate/client/cli" }
sp-core = { version = "2.0.0-dev", path = "../vendor/frontier/vendor/substrate/primitives/core" }
sc-executor = { version = "0.8.0-dev", path = "../vendor/frontier/vendor/substrate/client/executor" }
sc-service = { version = "0.8.0-dev", path = "../vendor/frontier/vendor/substrate/client/service" }
sp-inherents = { version = "2.0.0-dev", path = "../vendor/frontier/vendor/substrate/primitives/inherents" }
sc-transaction-pool = { version = "2.0.0-dev", path = "../vendor/frontier/vendor/substrate/client/transaction-pool" }
sp-transaction-pool = { version = "2.0.0-dev", path = "../vendor/frontier/vendor/substrate/primitives/transaction-pool" }
sc-network = { version = "0.8.0-dev", path = "../vendor/frontier/vendor/substrate/client/network" }
sc-consensus-aura = { version = "0.8.0-dev", path = "../vendor/frontier/vendor/substrate/client/consensus/aura" }
sp-consensus-aura = { version = "0.8.0-dev", path = "../vendor/frontier/vendor/substrate/primitives/consensus/aura" }
sc-consensus-manual-seal = { path = "../vendor/frontier/vendor/substrate/client/consensus/manual-seal" }
sp-consensus = { version = "0.8.0-dev", path = "../vendor/frontier/vendor/substrate/primitives/consensus/common" }
sc-consensus = { version = "0.8.0-dev", path = "../vendor/frontier/vendor/substrate/client/consensus/common" }
sp-timestamp = { version = "2.0.0-dev", default-features = false, path = "../vendor/frontier/vendor/substrate/primitives/timestamp" }
evm = { version = "2.0.0-dev", package = "pallet-evm", path = "../vendor/frontier/vendor/substrate/frame/evm" }
ethereum = { version = "0.1.0", package = "pallet-ethereum", path = "../vendor/frontier/frame/ethereum" }
sc-finality-grandpa = { version = "0.8.0-dev", path = "../vendor/frontier/vendor/substrate/client/finality-grandpa" }
sp-finality-grandpa = { version = "2.0.0-dev", path = "../vendor/frontier/vendor/substrate/primitives/finality-grandpa" }
sc-client-api = { version = "2.0.0-dev", path = "../vendor/frontier/vendor/substrate/client/api" }
sp-runtime = { version = "2.0.0-dev", path = "../vendor/frontier/vendor/substrate/primitives/runtime" }
sc-basic-authorship = { path = "../vendor/frontier/vendor/substrate/client/basic-authorship" }
sp-block-builder = { path = "../vendor/frontier/vendor/substrate/primitives/block-builder" }

frontier-consensus = { version = "0.1.0", path = "../vendor/frontier/consensus" }
banana-runtime = { version = "0.1.0-dev", path = "../runtime" }
frontier-rpc = { version = "0.1.0", path = "../vendor/frontier/rpc" }
frontier-rpc-primitives = { version = "0.1.0", path = "../vendor/frontier/rpc/primitives" }

[build-dependencies]
substrate-build-script-utils = { version = "2.0.0-dev", path = "../vendor/frontier/vendor/substrate/utils/build-script-utils" }
